In [1]:
import numpy as np

In [3]:
pip install numpy --user

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.0/20.0 MB 4.2 MB/s eta 0:00:0000:0100:01
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Note: you may need to restart the kernel to use updated packages.


In [33]:
a = np.arange(1)
a

array([0])

In [11]:
a = a.reshape((2,2))

In [57]:
b = np.broadcast_to(a, (2,3,4))
b

array([[[1.1, 1.1, 1.1, 1.1],
        [1.1, 1.1, 1.1, 1.1],
        [1.1, 1.1, 1.1, 1.1]],

       [[1.1, 1.1, 1.1, 1.1],
        [1.1, 1.1, 1.1, 1.1],
        [1.1, 1.1, 1.1, 1.1]]])

In [58]:
b.shape

(2, 3, 4)

In [59]:
c = b.sum((0,2))
c

array([8.8, 8.8, 8.8])

In [60]:
c.shape

(3,)

In [39]:
np.random.randn()

0.820393060858253

In [40]:
a = 1.1

In [64]:
a = np.random.randn(6, 6, 5, 4)
b = np.random.randn(4, 3)

In [66]:
np.matmul(a,b).shape

(6, 6, 5, 3)